// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46l26Bu8V_XX8KS_uR1iWYtUOgr-wyvo',
    appId: '1:114904702348:web:a27c3965cd338b8e484aa9',
    messagingSenderId: '114904702348',
    projectId: 'safewalk-46b90',
    authDomain: 'safewalk-46b90.firebaseapp.com',
    storageBucket: 'safewalk-46b90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05eJCztXzXtbCxAu58QrjDTBF9tuWae0',
    appId: '1:114904702348:android:191468bdada1cc64484aa9',
    messagingSenderId: '114904702348',
    projectId: 'safewalk-46b90',
    storageBucket: 'safewalk-46b90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIq-AwsVOufPalFoQO-AtL-Dyy1vECTCE',
    appId: '1:114904702348:ios:3fff9b5978994003484aa9',
    messagingSenderId: '114904702348',
    projectId: 'safewalk-46b90',
    storageBucket: 'safewalk-46b90.firebasestorage.app',
    iosBundleId: 'com.example.tempsafewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIq-AwsVOufPalFoQO-AtL-Dyy1vECTCE',
    appId: '1:114904702348:ios:3fff9b5978994003484aa9',
    messagingSenderId: '114904702348',
    projectId: 'safewalk-46b90',
    storageBucket: 'safewalk-46b90.firebasestorage.app',
    iosBundleId: 'com.example.tempsafewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB46l26Bu8V_XX8KS_uR1iWYtUOgr-wyvo',
    appId: '1:114904702348:web:e046c4c59f62f4eb484aa9',
    messagingSenderId: '114904702348',
    projectId: 'safewalk-46b90',
    authDomain: 'safewalk-46b90.firebaseapp.com',
    storageBucket: 'safewalk-46b90.firebasestorage.app',
  );
}
